.TH BEAN 1
.SH NAME
\fIbean\fR \- interpreter for bean programming language
.SH SYNOPSIS
.B bean
[option]
.IR file
.SH DESCRIPTION
.B \fIbean\fR
interprets bean file using STDIN as input.
.SH OPTIONS
.TP
.BR \-r ", " \-\-raw
Interpret \fIfile\fR as raw bean source. (Default)
.TP
.BR \-d ", " \-\-dump
Interpret \fIfile\fR as xxd\-style hexdump.
